### ISSUE TITLE
I trained the model for 20 hours in my PC with GTX-1060,Could you tell me how to test the model?

### ISSUE THREAD

**Issue by chenshuo0012** [thibo73800/capsnet_traffic_sign_classifier#3]
I trained the model in my PC with the GTX-1060, I interrupt the training use Ctrl+c
I get 4 files in checkpoints, they are: 
1.checkpoint
2.c2n_64_c1s_5_c1vl_16_c1s_9_c2d_0.7_c1nf_16_lr_0.0001_rs_1_c2vl_32_c1n_256_c2s_6--TrafficSign--1510475262.826812.data-00000-of-00001
3.c2n_64_c1s_5_c1vl_16_c1s_9_c2d_0.7_c1nf_16_lr_0.0001_rs_1_c2vl_32_c1n_256_c2s_6--TrafficSign--1510475262.826812.index
4.c2n_64_c1s_5_c1vl_16_c1s_9_c2d_0.7_c1nf_16_lr_0.0001_rs_1_c2vl_32_c1n_256_c2s_6--TrafficSign--1510475262.826812.meta
The content of the file in checkpoint is：
model_checkpoint_path: "/home/chenshuo/capsnet_traffic_sign_classifier/outputs/checkpoints/c2n_64_c1s_5_c1vl_16_c1s_9_c2d_0.7_c1nf_16_lr_0.0001_rs_1_c2vl_32_c1n_256_c2s_6--TrafficSign--1510475262.826812"
all_model_checkpoint_paths: "/home/chenshuo/capsnet_traffic_sign_classifier/outputs/checkpoints/c2n_64_c1s_5_c1vl_16_c1s_9_c2d_0.7_c1nf_16_lr_0.0001_rs_1_c2vl_32_c1n_256_c2s_6--TrafficSign--1510475262.826812"
I test the model use:
python3 test.py  outputs/checkpoints/c2n_64_c1s_5_c1vl_16_c1s_9_c2d_0.7_c1nf_16_lr_0.0001_rs_1_c2vl_32_c1n_256_c2s_6--TrafficSign--1510475262.826812 dataset/
The error is:
ModelBase::Loading ckpt ...
2017-11-13 10:41:21.279347: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-11-13 10:41:21.376162: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-13 10:41:21.376427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.56GiB
2017-11-13 10:41:21.376442: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from outputs/checkpoints/c2n_64_c1s_5_c1vl_16_c1s_9_c2d_0.7_c1nf_16_lr_0.0001_rs_1_c2vl_32_c1n_256_c2s_6--TrafficSign--1510475262.826812
Restoring parameters from outputs/checkpoints/c2n_64_c1s_5_c1vl_16_c1s_9_c2d_0.7_c1nf_16_lr_0.0001_rs_1_c2vl_32_c1n_256_c2s_6--TrafficSign--1510475262.826812
Traceback (most recent call last):
  File "test.py", line 100, in <module>
    test(arguments["<dataset>"], arguments["<ckpt>"])
  File "test.py", line 81, in test
    model.load(ckpt)
  File "/home/chenshuo/capsnet_traffic_sign_classifier/model_base.py", line 317, in load
    tensors = json.loads(tensors)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

Could you tell me why I can not test the model and what should I do?
Thank you.

**Comment by chenshuo0012** [comment]
I modified the code in model_base.py
line 317:
        tensors = json.loads(tensors.decode('utf-8'))
line 326:
        hyps = json.loads(hyps.decode('utf-8'))
Now, it seems OK.

**Comment by thibo73800** [comment]
Hum, Strange. Do you successfully test the model now?

**Comment by Bartcardi** [comment]
@chenshuo0012 Thank you very much, this issue also pops up if you restart training from saved checkpoint. Maybe a small change to the code? I can do a pull request.
